# configuration for "master" branch
# build in Debug mode and Test

-
  branches:
    only:
    - master

  environment:
    release_version: '0.9.1'

  version: $(release_version).{build}

  configuration: Debug

  services:
  - mssql2012sp1
  
  build:
    project: prefSQL.sln
    publish_nuget: true
    include_nuget_references: true

  before_build:
  - nuget restore

  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '{version}-dev'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'

  nuget:
    project_feed: true

- ps: 	
    $startPath = "$($env:appveyor_build_folder)\bin\Debug"
    $sqlInstance = "(local)\SQL2012SP1"
    $dbName = "ecommercetest"

    # replace the db connection with the local instance
    $config = join-path $startPath "App.config"
    $doc = (gc $config) -as [xml]
    $doc.SelectSingleNode('//connectionStrings/add[@name="unittest"]').connectionString = "Server=$sqlInstance; Database=$dbName; Trusted_connection=true"
    $doc.Save($config)
 
    # attach mdf to local instance
    $mdfFile = join-path $startPath "ecommercetest.mdf"
    $ldfFile = join-path $startPath "ecommercetest_log.ldf"
    sqlcmd -S "$sqlInstance" -Q "Use [master]; CREATE DATABASE [$dbName] ON (FILENAME = '$mdfFile'),(FILENAME = '$ldfFile') for ATTACH"